import { useMemo, useState } from "react";
import { Icon } from "./DashboardShared";

function formatClassTime(value) {
  if (!value) return "—";
  const [hour, minute] = String(value).split(":").map(Number);
  const suffix = hour >= 12 ? "PM" : "AM";
  const displayHour = hour % 12 || 12;
  return `${displayHour}:${String(minute).padStart(2, "0")} ${suffix}`;
}

export default function ClassesView({
  sections = [], section, importMasterList, importGradeSheet, importState,
  gradeSheetImportState, connectionStatus = "connecting", pendingSyncCount = 0,
  onOpenStudents, onOpenClassOptions, onDeleteClass,
}) {
  const [searchTerm, setSearchTerm] = useState("");
  const filteredSections = useMemo(
    () => sections.filter((item) => `${item.subject_code} ${item.subject_title} ${item.room}`.toLowerCase().includes(searchTerm.toLowerCase())),
    [sections, searchTerm],
  );
  const isOffline = connectionStatus === "offline";
  const isOnline = connectionStatus === "live" || connectionStatus === "online";
  const upload = (event, handler) => { const file = event.target.files?.[0]; if (file) handler(file); event.target.value = ""; };

  return <div className="flex min-h-full flex-col gap-6 bg-slate-50 p-6 text-slate-900 [font-family:system-ui,-apple-system,sans-serif] max-md:p-4">
    <header className="flex items-start justify-between gap-4 max-md:flex-col"><div><span className="text-xs font-bold uppercase tracking-[0.2em] text-indigo-500">Academic management</span><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-900">Classes &amp; Students</h1><p className="mt-1 text-sm text-slate-500">Manage sections, import students, sync grades, and handle daily attendance.</p></div><div className="flex items-center gap-3 text-xs font-semibold max-md:w-full max-md:flex-wrap"><div className={`flex items-center gap-2 rounded-full px-3 py-1.5 ${isOnline ? "bg-green-100 text-green-700" : isOffline ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-700"}`}><span className="h-2 w-2 rounded-full bg-current" />{isOnline ? "Connected" : isOffline ? "Offline" : "Connecting..."}</div>{pendingSyncCount > 0 && <div className="flex items-center gap-2 rounded-full bg-sky-100 px-3 py-1.5 text-sky-700"><Icon name="arrow" size={14} />{pendingSyncCount} pending syncs</div>}</div></header>
    <div className="grid grid-cols-[minmax(0,1fr)_340px] gap-6 max-lg:grid-cols-1"><section><div className="mb-5 flex gap-4"><label className="flex flex-1 items-center gap-2 rounded-[10px] border border-slate-200 bg-white px-3.5 py-2 text-slate-400 shadow-sm"><Icon name="search" size={16} /><input className="w-full border-0 bg-transparent text-sm text-slate-700 outline-none placeholder:text-slate-400" placeholder="Search by code, title, or room..." value={searchTerm} onChange={(event) => setSearchTerm(event.target.value)} /></label></div><div className="grid grid-cols-[repeat(auto-fill,minmax(280px,1fr))] gap-4">{filteredSections.length ? filteredSections.map((item) => <article className={`flex flex-col justify-between rounded-[14px] border bg-white p-[18px] shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg ${item.id === section?.id ? "border-indigo-400 ring-2 ring-indigo-100" : "border-slate-200"}`} key={item.id}><div><div className="flex items-start justify-between gap-3"><div><span className="rounded-md bg-indigo-50 px-2 py-1 text-[11px] font-bold uppercase text-indigo-600">{item.subject_code || "No code"}</span><h2 className="mt-2 text-base font-semibold text-slate-800">{item.subject_title || "Untitled class"}</h2></div><button className="rounded-md p-1 text-slate-400 transition hover:bg-red-50 hover:text-red-500" title="Delete class" type="button" onClick={() => onDeleteClass(item)}><Icon name="trash" size={16} /></button></div><div className="mb-4 mt-4 flex flex-col gap-2 text-[13px] text-slate-500"><div className="flex items-center gap-2"><Icon name="calendar" size={14} />{item.days || "Schedule unset"}</div><div className="flex items-center gap-2"><Icon name="clock" size={14} />{formatClassTime(item.time_start)} - {formatClassTime(item.time_end)}</div>{item.room && <div className="flex items-center gap-2"><Icon name="location" size={14} />Room {item.room}</div>}</div></div><div className="grid grid-cols-2 gap-2 border-t border-slate-100 pt-3"><button className="inline-flex items-center justify-center gap-1.5 rounded-lg border border-slate-200 px-2 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-50" type="button" onClick={() => onOpenStudents(item.id)}><Icon name="users" size={15} />Students</button><button className="inline-flex items-center justify-center gap-1.5 rounded-lg border border-indigo-200 px-2 py-2 text-xs font-semibold text-indigo-600 hover:bg-indigo-50" type="button" onClick={() => onOpenClassOptions(item.id)}><Icon name="settings" size={15} />Manage</button></div></article>) : <div className="col-span-full flex min-h-40 flex-col items-center justify-center rounded-[14px] border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500"><Icon name="file" size={32} /><p className="mt-3">{searchTerm ? "No class sections match your search." : "Import a master list to create your first class."}</p></div>}</div></section>
      <aside className="rounded-[14px] border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex gap-3 text-slate-900"><Icon name="arrow" size={18} /><div><h2 className="font-bold">Import Center</h2><p className="mt-1 text-xs leading-5 text-slate-500">Upload Excel files to update class students and scores.</p></div></div><div className="flex flex-col gap-4"><div className="rounded-[10px] border border-dashed border-slate-300 bg-slate-50 p-3 text-center"><h3 className="text-[13px] font-semibold text-slate-700">Master student list</h3><p className="mb-3 mt-1 text-[11px] text-slate-500">Import student IDs and names.</p><label className="inline-flex cursor-pointer items-center gap-1.5 rounded-md bg-blue-500 px-3 py-1.5 text-xs font-medium text-white hover:bg-blue-600"><Icon name="file" size={16} />Choose file<input className="hidden" type="file" accept=".xlsx,.xls,.csv" onChange={(event) => upload(event, importMasterList)} /></label></div><div className="rounded-[10px] border border-dashed border-slate-300 bg-slate-50 p-3 text-center"><h3 className="text-[13px] font-semibold text-slate-700">Grade sheets</h3><p className="mb-3 mt-1 text-[11px] text-slate-500">Upload completed assessment sheets.</p><label className="inline-flex cursor-pointer items-center gap-1.5 rounded-md bg-blue-500 px-3 py-1.5 text-xs font-medium text-white hover:bg-blue-600"><Icon name="chart" size={16} />Choose file<input className="hidden" type="file" accept=".xlsx,.xls,.xlsm,.csv" disabled={gradeSheetImportState?.status === "working"} onChange={(event) => upload(event, importGradeSheet)} /></label></div>{importState?.message && <p className="text-xs text-slate-500" role="status">{importState.message}</p>}{gradeSheetImportState?.message && <p className="text-xs text-slate-500" role="status">{gradeSheetImportState.message}</p>}</div></aside>
    </div>
  </div>;
}
