import { useState } from "react";
import { useDashboardViewModel } from "../ViewModels/useDashboardViewModel";
import { navItems } from "../Models/dashboardModel";
import ClassActionModal from "./ClassActionModal";
import ClassesView from "./ClassesView";
import OverviewView from "./OverviewView";
import ReportsView from "./ReportsView";
import { Avatar, Icon } from "./DashboardShared";
import logo from "../../assets/Logo.png";
import "../../App.css";

function ClassOptionsModal({ section, onClose, onOpenAction, onOpenStudentView, onSyncToExcel, syncReady }) {
  const actions = [["attendance", "Take Attendance"], ["attendance-list", "Attendance List"], ["create-assessment", "Create Assessment"], ["manage-assessments", "Manage Assessments"], ["record-score", "Record Score"], ["show-grades", "Show Grades"], ["grade-summary", "Record Summary"], ["grade-settings", "Grade Sheet Settings"]];
  return <div className="modal-backdrop class-options-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="class-options-modal" role="dialog" aria-modal="true" aria-labelledby="class-options-title"><div className="class-options-header"><h2 id="class-options-title">CLASS OPTIONS</h2><button className="modal-close class-options-close" onClick={onClose} aria-label="Close class options">×</button></div><div className="class-options-body"><div className="class-option-summary"><div><h3>{section?.subject_code || "Class"} - {section?.subject_title || "Class subject"}</h3><p>{section?.days || "Schedule not set"} · {section?.room || "Room not set"}</p></div></div>{actions.map(([type, label]) => <button className="class-option-button" key={type} onClick={() => { onClose(); onOpenAction(type, section.id); }}>{label}</button>)}<button className="class-option-button" onClick={() => { onClose(); onOpenStudentView(section.id); }}>Open Student View</button><button className="class-option-button" disabled={!syncReady} onClick={() => { onClose(); void onSyncToExcel(); }}>{syncReady ? "Sync to Excel" : "Loading class data..."}</button><button className="class-option-button" onClick={() => { onClose(); onOpenAction("add-student", section.id); }}>Add Student</button></div></section></div>;
}

function StudentModal({ section, students, onClose }) {
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="student-modal" role="dialog" aria-modal="true" aria-labelledby="student-modal-title"><div className="student-modal-header"><div><p className="eyebrow">CLASS ROSTER</p><h2 id="student-modal-title">{section?.subject_code || "Students"}</h2><p>{section?.subject_title || "Students enrolled in this class"}</p></div><button className="modal-close" onClick={onClose} aria-label="Close students">×</button></div><div className="table-wrap student-modal-table"><table><thead><tr><th>#</th><th>STUDENT ID</th><th>NAME</th><th>GENDER</th><th>ATTENDANCE</th><th>GRADE</th></tr></thead><tbody>{students.map((student, index) => <tr key={student.id}><td>{index + 1}</td><td>{student.number}</td><td>{student.name}</td><td>{student.gender === "F" ? "Female" : student.gender === "M" ? "Male" : "—"}</td><td>{student.attendance}%</td><td>{Number(student.grade || 0).toFixed(2)}</td></tr>)}</tbody></table>{!students.length && <div className="empty-state">No students have been imported for this class.</div>}</div></section></div>;
}

function DeleteClassModal({ section, deleting, error, onClose, onConfirm }) {
  return <div className="modal-backdrop delete-confirm-backdrop" onMouseDown={(event) => event.target === event.currentTarget && !deleting && onClose()}><section className="delete-confirm-modal" role="alertdialog" aria-modal="true"><div className="delete-confirm-icon"><Icon name="trash" size={22} /></div><p className="delete-confirm-kicker">PERMANENT ACTION</p><h2>Delete this class?</h2><p>This will delete <strong>{section?.subject_code || "this class"}</strong>, including its students, scores, grades, and attendance records.</p>{error && <p className="delete-confirm-error">{error}</p>}<div className="delete-confirm-actions"><button className="outline-button" onClick={onClose} disabled={deleting}>Cancel</button><button className="danger-button" onClick={onConfirm} disabled={deleting}>{deleting ? "Deleting…" : "Delete class"}</button></div></section></div>;
}

export default function DashboardShell() {
  const viewModel = useDashboardViewModel();
  const [classOptionsId, setClassOptionsId] = useState(null);
  const [studentModalId, setStudentModalId] = useState(null);
  const [actionModal, setActionModal] = useState(null);
  const [deleteClass, setDeleteClass] = useState(null);
  const [deleteError, setDeleteError] = useState("");
  const [deletingClass, setDeletingClass] = useState(false);
  const selectedSection = viewModel.sections.find((item) => item.id === viewModel.section?.id) ?? viewModel.section;
  const optionsSection = viewModel.sections.find((item) => item.id === classOptionsId);
  const studentSection = viewModel.sections.find((item) => item.id === studentModalId);
  const actionSection = viewModel.sections.find((item) => item.id === actionModal?.sectionId);
  const actionReady = selectedSection?.id === actionModal?.sectionId;
  const selectSection = (sectionId) => viewModel.selectSection(sectionId);
  const openClassOptions = (sectionId) => { selectSection(sectionId); setClassOptionsId(sectionId); };
  const openAction = (type, sectionId = selectedSection?.id) => { if (sectionId) selectSection(sectionId); setActionModal({ type, sectionId }); };
  const openStudentView = (sectionId) => window.open(`${window.location.origin}/?view=student&section=${encodeURIComponent(sectionId)}`, "_blank", "noopener,noreferrer");
  const confirmDelete = async () => { if (!deleteClass) return; setDeletingClass(true); setDeleteError(""); try { await viewModel.deleteSection(deleteClass.id); setDeleteClass(null); } catch (error) { setDeleteError(error.message || "The class could not be deleted."); } finally { setDeletingClass(false); } };
  const closeAction = () => setActionModal(null);
  const page = viewModel.active === "classes" ? <ClassesView sections={viewModel.sections} section={selectedSection} importMasterList={viewModel.importMasterList} importGradeSheet={viewModel.importGradeSheet} importState={viewModel.importState} gradeSheetImportState={viewModel.gradeSheetImportState} connectionStatus={viewModel.connectionStatus} pendingSyncCount={viewModel.pendingSyncCount} onOpenStudents={(sectionId) => { setStudentModalId(sectionId); selectSection(sectionId); }} onOpenClassOptions={openClassOptions} onDeleteClass={(item) => { setDeleteError(""); setDeleteClass(item); }} /> : viewModel.active === "reports" ? <ReportsView /> : <OverviewView setActive={viewModel.setActive} students={viewModel.students} stats={viewModel.stats} sections={viewModel.sections} onOpenClassOptions={openClassOptions} onOpenAction={openAction} />;
  const actionProps = { type: actionModal?.type, section: actionSection, students: actionReady ? viewModel.students : [], assessmentScores: actionReady ? viewModel.assessmentScores : [], assessmentDefinitions: actionReady ? viewModel.assessmentDefinitions : [], sessions: actionReady ? viewModel.sessions : [], attendanceSessions: actionReady ? viewModel.attendanceSessions : [], gradingPeriods: actionReady ? viewModel.gradingPeriods : [], stats: actionReady ? viewModel.stats : { sessionsHeld: 0, monthAttendance: "—", classAverage: "—", passingRate: "—", excellentCount: 0, needsReviewCount: 0 }, loading: !actionReady, onClose: closeAction, onSaveAttendance: async (payload) => { await viewModel.saveAttendance(payload); closeAction(); }, onSaveAssessmentScores: async (payload) => { await viewModel.saveAssessmentScores(payload); closeAction(); }, onAutoSaveAssessmentScores: viewModel.saveAssessmentScores, onSaveAssessment: viewModel.saveAssessment, onUpdateAssessment: viewModel.updateAssessment, onGrantAssessmentAttempt: viewModel.grantAssessmentAttempt, onDeleteAssessment: viewModel.deleteAssessment, onSubmitAssessment: viewModel.submitAssessment, onSaveGradingPeriods: async (payload) => { await viewModel.saveGradingPeriods(payload); closeAction(); }, onAddStudent: async (payload) => { await viewModel.addStudent(payload); closeAction(); }, onRefreshGrades: viewModel.refreshGrades };
  return <div className="app-shell"><aside className={`sidebar ${viewModel.mobileNav ? "sidebar-open" : ""}`}><div className="brand"><img className="brand-logo" src={logo} alt="Presenzio" /></div><div className="sidebar-section"><p className="nav-label">WORKSPACE</p><nav aria-label="Workspace navigation">{navItems.map((item) => <button className={`nav-item ${viewModel.active === item.id ? "active" : ""}`} key={item.id} onClick={() => { viewModel.setActive(item.id); viewModel.setMobileNav(false); }}><Icon name={item.icon} size={18} /><span>{item.label}</span></button>)}</nav></div><div className="sidebar-bottom"><button className="nav-item" type="button"><Icon name="settings" size={18} /><span>Settings</span></button><div className="profile"><Avatar initials="JM" color="blue" small /><span><b>Jeorge Mancilla</b><small>Teacher account</small></span></div></div></aside><main className="main-content"><header className="topbar"><button className="mobile-menu" onClick={() => viewModel.setMobileNav(!viewModel.mobileNav)} aria-label="Toggle navigation"><span /><span /><span /></button><div className="breadcrumb"><span>{navItems.find((item) => item.id === viewModel.active)?.label || "Overview"}</span><b>/</b><strong>{selectedSection?.subject_code || "No section"}</strong></div><div className="topbar-actions"><span className="connection-status">{viewModel.connectionMessage}</span><Avatar initials="JM" color="blue" small /></div></header><div className="content-wrap">{page}</div></main>{optionsSection && <ClassOptionsModal section={optionsSection} onClose={() => setClassOptionsId(null)} onOpenAction={openAction} onOpenStudentView={openStudentView} onSyncToExcel={viewModel.syncToExcel} syncReady={selectedSection?.id === optionsSection.id} />}{studentModalId && <StudentModal section={studentSection} students={selectedSection?.id === studentModalId ? viewModel.students : []} onClose={() => setStudentModalId(null)} />}{deleteClass && <DeleteClassModal section={deleteClass} deleting={deletingClass} error={deleteError} onClose={() => !deletingClass && setDeleteClass(null)} onConfirm={confirmDelete} />}{actionModal && actionSection && <ClassActionModal {...actionProps} />}</div>;
}
