import { useMemo } from "react";
import { useAuth } from "../../auth/useAuth";
import { useDashboardState } from "./useDashboardState";
import { useDashboardOfflineData } from "./dashboardOfflineData";
import { useDashboardLiveLoader } from "./dashboardLiveLoader";
import { useDashboardCoordinator } from "./dashboardCoordinator";
import {
  emptyStats,
  gradingWeights,
  assessmentItemLimits,
  transmutationBreakpoints,
} from "./dashboardConstants";
import {
  transmutePercentage,
  formatDate,
  formatDay,
  formatShortDate,
  resolvePeriodCodeForSession,
  average,
  toGradeRows,
  createAssessmentAccessKey,
  browserIsOffline,
  createLocalId,
  isNetworkError,
  serializeAssessmentDate,
  answerSimilarity,
} from "./dashboardUtils";
export function useDashboardViewModel({ accountScoped = true } = {}) {
  const { user } = useAuth();
  const accountId = user?.id ?? null;
  const state = useDashboardState();
  const {
    active,
    setActive,
    mobileNav,
    setMobileNav,
    period,
    setPeriod,
    category,
    setCategory,
    query,
    setQuery,
    students,
    setStudents,
    gradeRows,
    setGradeRows,
    gradingPeriods,
    setGradingPeriods,
    assessmentScores,
    setAssessmentScores,
    assessmentDefinitions,
    setAssessmentDefinitions,
    studentGroups,
    setStudentGroups,
    assessmentAttempts,
    setAssessmentAttempts,
    assessmentAttemptGrants,
    setAssessmentAttemptGrants,
    assessmentViolations,
    setAssessmentViolations,
    attendanceSessions,
    setAttendanceSessions,
    sessions,
    setSessions,
    sections,
    setSections,
    stats,
    setStats,
    section,
    setSection,
    connectionStatus,
    setConnectionStatus,
    connectionMessage,
    setConnectionMessage,
    pendingSyncCount,
    setPendingSyncCount,
    importState,
    setImportState,
    gradeSheetImportState,
    setGradeSheetImportState,
    loadRequestIdRef,
  } = state;
  const currentSectionId = section?.id;

  const filteredStudents = useMemo(
    () =>
      students
        .filter((student) =>
          student.name.toLowerCase().includes(query.toLowerCase()),
        )
        .sort((first, second) =>
          first.name.localeCompare(second.name, undefined, {
            sensitivity: "base",
          }),
        ),
    [query, students],
  );

  const { clearLiveData, applyOfflineSnapshot, loadOfflineData } =
    useDashboardOfflineData({
      setSection,
      setSections,
      setStudents,
      setGradeRows,
      setGradingPeriods,
      setAssessmentScores,
      setAssessmentDefinitions,
      setStudentGroups,
      setAssessmentAttempts,
      setAssessmentAttemptGrants,
      setAssessmentViolations,
      setAttendanceSessions,
      setSessions,
      setStats,
      setConnectionStatus,
      setConnectionMessage,
      setPendingSyncCount,
      loadRequestIdRef,
    });

  const loadLiveData = useDashboardLiveLoader({
    accountId,
    accountScoped,
    currentSectionId,
    section,
    students,
    gradingPeriods,
    assessmentScores,
    assessmentDefinitions,
    studentGroups,
    loadOfflineData,
    clearLiveData,
    loadRequestIdRef,
    setSection,
    setSections,
    setStudents,
    setGradeRows,
    setGradingPeriods,
    setAssessmentScores,
    setAssessmentAttempts,
    setAssessmentAttemptGrants,
    setAssessmentViolations,
    setAssessmentDefinitions,
    setStudentGroups,
    setAttendanceSessions,
    setSessions,
    setStats,
    setConnectionStatus,
    setConnectionMessage,
  });

  const actions = useDashboardCoordinator({
    accountId,
    accountScoped,
    currentSectionId,
    period,
    section,
    sections,
    students,
    gradeRows,
    gradingPeriods,
    assessmentScores,
    assessmentDefinitions,
    studentGroups,
    assessmentAttempts,
    assessmentAttemptGrants,
    assessmentViolations,
    attendanceSessions,
    sessions,
    stats,
    loadLiveData,
    clearLiveData,
    setSection,
    setSections,
    setStudents,
    setGradingPeriods,
    setAssessmentScores,
    setAssessmentDefinitions,
    setStudentGroups,
    setAssessmentAttempts,
    setAssessmentAttemptGrants,
    setAssessmentViolations,
    setAttendanceSessions,
    setConnectionStatus,
    setConnectionMessage,
    setPendingSyncCount,
    setImportState,
    setGradeSheetImportState,
    helpers: {
      answerSimilarity,
      assessmentItemLimits,
      average,
      browserIsOffline,
      createAssessmentAccessKey,
      createLocalId,
      formatShortDate,
      gradingWeights,
      isNetworkError,
      serializeAssessmentDate,
      transmutePercentage,
    },
  });
const {
  selectSection,
  saveGradingPeriods,
  importMasterList,
  syncToExcel,
  refreshGrades,
  importGradeSheet,
  saveAttendance,
  deleteAttendance,
  saveGrades,
  saveAssessmentScores,
  saveAssessment,
  updateAssessment,
  deleteAssessment,
  saveStudentGroup,
  deleteStudentGroup,
  grantAssessmentAttempt,
  loadStudentAssessment,
  submitAssessment,
  addStudent,
  updateStudent,
  deleteStudent,
  transferStudent,
  loadTransferPreview,
  updateSection,
  deleteSection,
  flushOfflineMutations,
} = actions;

  return {
    active,
    mobileNav,
    period,
    category,
    query,
    students,
    assessmentScores,
    attendanceSessions,
    gradeRows,
    sessions,
    stats,
    section,
    sections,
    gradingPeriods,
    filteredStudents,
    connectionStatus,
    connectionMessage,
    pendingSyncCount,
    importState,
    gradeSheetImportState,
    importMasterList,
    importGradeSheet,
    syncToExcel,
    setActive,
    setMobileNav,
    setPeriod,
    setCategory,
    setQuery,
    selectSection,
    saveGradingPeriods,
    saveAttendance,
    deleteAttendance,
    saveGrades,
    saveAssessmentScores,
    saveAssessment,
    updateAssessment,
    grantAssessmentAttempt,
    deleteAssessment,
    assessmentDefinitions,
    studentGroups,
    saveStudentGroup,
    deleteStudentGroup,
    assessmentAttempts,
    assessmentAttemptGrants,
    assessmentViolations,
    loadStudentAssessment,
    submitAssessment,
    addStudent,
    updateStudent,
    deleteStudent,
    transferStudent,
    loadTransferPreview,
    updateSection,
    deleteSection,
    refreshGrades,
    refresh: loadLiveData,
  };
}
